spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/greengram2
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: green502


mybatis:
  mapper-locations: mappers/**/*.xml


springdoc:
  swagger-ui:
    path: /swagger.html

server:
  port: 8088
